spring.application.name=spring-security-jwt-practice

server.port=8080

jwt.secret=MySecretKeyMySecretKeyMySecretKey12345

logging.level.org.springframework.security=DEBUG

spring-boot-starter-data-jpa
mysql-connector-j